/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caculator;

import javax.script.*;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;

/**
 *
 * @author quyle
 */
public class CaculatorFrame extends javax.swing.JFrame {

    public String textResult = "";
    public int mode = 0;
    public int status = 0;

    public double length, width;
    public double aSide, bSide, cSide;

    /**
     * Creates new form CaculatorFrame
     */
    public CaculatorFrame() {
        initComponents();
        refreshScreen(textResult);
    }

    public void refreshScreen(String text) {
        this.screen.setText(text);
    }

    public String removeLastChar(String str) {
        if (str != null && str.length() > 0) {
            StringBuilder sb = new StringBuilder(str);
            sb.deleteCharAt(str.length() - 1);
            return sb.toString();
        }
        return str;
    }

    public double evaluateExpression(String expression) throws ScriptException {
        Expression e = new ExpressionBuilder(expression).build();
        return e.evaluate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        allClear = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        div = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        openBracket = new javax.swing.JButton();
        closeBracket = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        up1 = new javax.swing.JButton();
        up4 = new javax.swing.JButton();
        up5 = new javax.swing.JButton();
        up6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        square = new javax.swing.JButton();
        rectangle = new javax.swing.JButton();
        triangle = new javax.swing.JButton();
        circle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        screen.setColumns(20);
        screen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        screen.setRows(5);
        jScrollPane1.setViewportView(screen);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        num7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        jPanel1.add(num7);

        num8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        jPanel1.add(num8);

        num9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        jPanel1.add(num9);

        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("DEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);

        allClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allClear.setText("AC");
        allClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearActionPerformed(evt);
            }
        });
        jPanel1.add(allClear);

        num4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        jPanel1.add(num4);

        num5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel1.add(num5);

        num6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        jPanel1.add(num6);

        multi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        multi.setText("*");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        jPanel1.add(multi);

        div.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel1.add(div);

        num1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        jPanel1.add(num1);

        num2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel1.add(num2);

        num3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        jPanel1.add(num3);

        plus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        jPanel1.add(plus);

        minus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        jPanel1.add(minus);

        num0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        jPanel1.add(num0);

        dot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });
        jPanel1.add(dot);

        openBracket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        openBracket.setText("(");
        openBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBracketActionPerformed(evt);
            }
        });
        jPanel1.add(openBracket);

        closeBracket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeBracket.setText(")");
        closeBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBracketActionPerformed(evt);
            }
        });
        jPanel1.add(closeBracket);

        equal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel1.add(equal);

        jPanel2.setLayout(null);

        up1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        up1.setText("Right");
        jPanel2.add(up1);
        up1.setBounds(130, 50, 60, 40);

        up4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        up4.setText("Up");
        jPanel2.add(up4);
        up4.setBounds(60, 10, 70, 40);

        up5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        up5.setText("Left");
        jPanel2.add(up5);
        up5.setBounds(0, 50, 60, 40);

        up6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        up6.setText("Down");
        jPanel2.add(up6);
        up6.setBounds(60, 90, 70, 40);

        jPanel3.setLayout(new java.awt.GridLayout());

        square.setText("Square");
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });
        jPanel3.add(square);

        rectangle.setText("Rectangle");
        rectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleActionPerformed(evt);
            }
        });
        jPanel3.add(rectangle);

        triangle.setText("Triangle");
        triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleActionPerformed(evt);
            }
        });
        jPanel3.add(triangle);

        circle.setText("Circle");
        circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleActionPerformed(evt);
            }
        });
        jPanel3.add(circle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        this.textResult += "0";
        refreshScreen(textResult);
    }//GEN-LAST:event_num0ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        this.textResult += "1";
        refreshScreen(textResult);
    }//GEN-LAST:event_num1ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        this.textResult += "3";
        refreshScreen(textResult);
    }//GEN-LAST:event_num3ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        this.textResult += "2";
        refreshScreen(textResult);
    }//GEN-LAST:event_num2ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        this.textResult += "4";
        refreshScreen(textResult);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        this.textResult += "5";
        refreshScreen(textResult);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        this.textResult += "6";
        refreshScreen(textResult);
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        this.textResult += "7";
        refreshScreen(textResult);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        this.textResult += "8";
        refreshScreen(textResult);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        this.textResult += "9";
        refreshScreen(textResult);
    }//GEN-LAST:event_num9ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        this.textResult = removeLastChar(textResult);
        refreshScreen(textResult);
    }//GEN-LAST:event_deleteActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
        this.textResult += ".";
        refreshScreen(textResult);
    }//GEN-LAST:event_dotActionPerformed

    private void openBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBracketActionPerformed
        // TODO add your handling code here:
        this.textResult += "(";
        refreshScreen(textResult);
    }//GEN-LAST:event_openBracketActionPerformed

    private void closeBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBracketActionPerformed
        // TODO add your handling code here:
        this.textResult += ")";
        refreshScreen(textResult);
    }//GEN-LAST:event_closeBracketActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        switch (mode) {
            case 0:
                try {
                    if (textResult == null) {
                        refreshScreen(textResult);
                    } else {
                        textResult += "\n\n\n\n\n" + evaluateExpression(textResult);
                        refreshScreen(textResult);
                    }
                } catch (ScriptException e) {
                    textResult += "\n\n\n\n\n" + "Lỗi phép tính!";
                    refreshScreen(textResult);
                }
                break;
            case 1:
                String[] words1 = textResult.split(" ");
                String sideStr1 = words1[words1.length - 1];
                double side1 = Double.parseDouble(sideStr1);
                double squareArea = side1 * side1;
                textResult += "\n\n\n\n\n" + "Diện tích hình vuông: " + squareArea;
                refreshScreen(textResult);
                break;
            case 2:
                if (status == 0) {
                    String[] lengthWords2 = textResult.split(" ");
                    String lenghtStr = lengthWords2[lengthWords2.length - 1];
                    length = Double.parseDouble(lenghtStr);
                    textResult += "\nChiều rộng: ";
                    refreshScreen(textResult);
                    status++;
                } else if (status == 1) {
                    String[] widthWords2 = textResult.split(" ");
                    String widthStr = widthWords2[widthWords2.length - 1];
                    width = Double.parseDouble(widthStr);
                    double rectArea = length * width;
                    textResult += "\n\n\n\n" + "Diện tích hình chữ nhật: " + rectArea;
                    refreshScreen(textResult);
                    status++;
                }
                break;
            case 3:
                if (status == 0) {
                    String[] aWords = textResult.split(" ");
                    String aStr = aWords[aWords.length - 1];
                    aSide = Double.parseDouble(aStr);
                    textResult += "\nCạnh B: ";
                    refreshScreen(textResult);
                    status++;
                } else if (status == 1) {
                    String[] bWords = textResult.split(" ");
                    String bStr = bWords[bWords.length - 1];
                    bSide = Double.parseDouble(bStr);
                    textResult += "\nCạnh C: ";
                    refreshScreen(textResult);
                    status++;
                } else if (status == 2) {
                    String[] cWords = textResult.split(" ");
                    String cStr = cWords[cWords.length - 1];
                    cSide = Double.parseDouble(cStr);
                    double halfArea = (aSide + bSide + cSide) / 2.0;
                    double triangleArea = Math.sqrt(halfArea * (halfArea - aSide) * (halfArea - bSide) * (halfArea - cSide));
                    textResult += "\n\n\n" + "Diện tích hình tam giác: " + triangleArea;
                    refreshScreen(textResult);
                    status++;
                }
                break;
            case 4:
                String[] words4 = textResult.split(" ");
                String radianStr4 = words4[words4.length - 1];
                double radian4 = Double.parseDouble(radianStr4);
                double circleArea = radian4 * radian4 * 3.1415926;
                textResult += "\n\n\n\n\n" + "Diện tích hình tròn: " + circleArea;
                refreshScreen(textResult);
                break;
        }
    }//GEN-LAST:event_equalActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        this.textResult += "+";
        refreshScreen(textResult);
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        this.textResult += "-";
        refreshScreen(textResult);
    }//GEN-LAST:event_minusActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        this.textResult += "*";
        refreshScreen(textResult);
    }//GEN-LAST:event_multiActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
        this.textResult += "/";
        refreshScreen(textResult);
    }//GEN-LAST:event_divActionPerformed

    private void allClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allClearActionPerformed
        // TODO add your handling code here:
        this.textResult = "";
        this.mode = 0;
        this.status = 0;
        refreshScreen(textResult);
    }//GEN-LAST:event_allClearActionPerformed

    private void rectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleActionPerformed
        // TODO add your handling code here:
        mode = 2;
        status = 0;
        textResult = "Chiều dài: ";
        refreshScreen(textResult);
    }//GEN-LAST:event_rectangleActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        // TODO add your handling code here:
        mode = 1;
        status = 0;
        textResult = "Chiều dài cạnh: ";
        refreshScreen(textResult);
    }//GEN-LAST:event_squareActionPerformed

    private void circleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleActionPerformed
        // TODO add your handling code here:
        mode = 4;
        status = 0;
        textResult = "Bán kính: ";
        refreshScreen(textResult);
    }//GEN-LAST:event_circleActionPerformed

    private void triangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleActionPerformed
        // TODO add your handling code here:
        mode = 3;
        status = 0;
        textResult = "Cạnh A: ";
        refreshScreen(textResult);
    }//GEN-LAST:event_triangleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allClear;
    private javax.swing.JButton circle;
    private javax.swing.JButton closeBracket;
    private javax.swing.JButton delete;
    private javax.swing.JButton div;
    private javax.swing.JButton dot;
    private javax.swing.JButton equal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minus;
    private javax.swing.JButton multi;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton openBracket;
    private javax.swing.JButton plus;
    private javax.swing.JButton rectangle;
    private javax.swing.JTextArea screen;
    private javax.swing.JButton square;
    private javax.swing.JButton triangle;
    private javax.swing.JButton up1;
    private javax.swing.JButton up4;
    private javax.swing.JButton up5;
    private javax.swing.JButton up6;
    // End of variables declaration//GEN-END:variables
}
